# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cup_name', models.CharField(blank=True, max_length=30, null=True)),
                ('cup_year', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cups',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('score_a', models.SmallIntegerField(db_column='score_A')),
                ('score_b', models.SmallIntegerField(db_column='score_B')),
                ('score_prolong_a', models.SmallIntegerField(blank=True, db_column='score_prolong_A', null=True)),
                ('score_prolong_b', models.SmallIntegerField(blank=True, db_column='score_prolong_B', null=True)),
                ('score_tab_a', models.SmallIntegerField(blank=True, db_column='score_tab_A', null=True)),
                ('score_tab_b', models.SmallIntegerField(blank=True, db_column='score_tab_B', null=True)),
                ('phase', models.CharField(blank=True, max_length=15, null=True)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('cup', models.ForeignKey(db_column='cup', on_delete=django.db.models.deletion.DO_NOTHING, to='pronos.Cups')),
            ],
            options={
                'db_table': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamsByCup',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('fifa_rank', models.SmallIntegerField(blank=True, null=True)),
                ('cup', models.ForeignKey(db_column='cup', on_delete=django.db.models.deletion.DO_NOTHING, to='pronos.Cups')),
                ('team', models.ForeignKey(db_column='team', on_delete=django.db.models.deletion.DO_NOTHING, to='pronos.Teams')),
            ],
            options={
                'db_table': 'Teams_by_cup',
            },
        ),
        migrations.AddField(
            model_name='matches',
            name='team_a',
            field=models.ForeignKey(db_column='team_A', on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_a', to='pronos.Teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_b',
            field=models.ForeignKey(db_column='team_B', on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_b', to='pronos.Teams'),
        ),
    ]
